### ISSUE TITLE
Redis container runAsUser and fsGroup permissions are incorrect

### ISSUE THREAD

**Issue by CH-JosephBironas** [sourcegraph/deploy-sourcegraph#191] opened 2019-02-12 17:48 UTC
Issue: 
The redis-cache pod tries to checkpoint to disk at /redis-data using the default config. This creates an error due to runAsUser being set to 0, but the main process doesn't assume that role at start. It runs as redis, uid:100 and gid:101.

This generates excessive logging of lines like:
```
1:M 12 Feb 17:24:41.025 * Background saving started by pid 37
37:C 12 Feb 17:24:41.025 # Failed opening the RDB file dump.rdb (in server root dir /redis-data) for saving: Permission denied
1:M 12 Feb 17:24:41.125 # Background saving error
```

Workaround:
Set the securityContext, runAsUser: 100, and fsGroup: 101, and restart the pod. 

Log lines now look normal:
```
1:M 12 Feb 17:45:39.040 * Background saving started by pid 28
28:C 12 Feb 17:45:39.060 * DB saved on disk
28:C 12 Feb 17:45:39.061 * RDB: 2 MB of memory used by copy-on-write
1:M 12 Feb 17:45:39.140 * Background saving terminated with success
```

**Comment by tsenart** [comment] 2019-02-12 18:58
Has this changed recently? @ggilmore: What made you assign this to us? Please excuse the short-memory :)

**Comment by tsenart** [comment] 2019-04-17 12:12
Duplicate of sourcegraph/sourcegraph#3254.

**Closed by tsenart** 2019-04-17 12:12 UTC
Labels: deploy-sourcegraph, deployment
